ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),   
    path("", include("store.urls")),
    path("user/", include("userauths.urls")),
]

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from store.views import index
from .views import shop_view, about_view, contact_view, blog_view, services_view , cart_view,checkout_view, search_view, details_view,cart_vieww, payment_completed_view, chambre_view, cuisine_view, salon_view
app_name = "store"

urlpatterns = [
    path("", index, name="index"),
    path("shop/", shop_view, name="shop_view"),
    path("about/", about_view, name="about_view"),
    path("contact/", contact_view, name="contact_view"),
    path("blog/", blog_view, name="blog_view"),
    path("services/", services_view, name="services_view"),
    path("cart/<pid>", cart_view, name="cart_view"),
    path("cart/", cart_vieww, name="cart_vieww"),
    path("cart-v/", cart_vieww, name="cart_v"),

    path("checkout/", checkout_view, name="checkout_view"),
    path("search/", search_view, name="search_view"),
    path("details/<pid>",details_view ,name="details_view"),
    path('paypal/', include('paypal.standard.ipn.urls')),

    path("paiement_completed/",payment_completed_view ,name="payment_completed"),
    path("chambre/",chambre_view ,name="chambre_view"),
    path("cuisine/",cuisine_view ,name="cuisine_view"),
    path("salon/",salon_view ,name="salon_view"),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_views, name="sign-up"),
    path("sign-in/", views.login_views, name="sign-in"),
    path("sign-out/", views.logout_views, name="sign-out"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser) :
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username',]

    def __str__(self):
        return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User
from django.contrib.auth.forms import AuthenticationForm


class UserRegisterForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder":"Username"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control","placeholder":"Email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control","placeholder":"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control","placeholder":"Confirm Password"}))

    class Meta : 
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import logout

User = settings.AUTH_USER_MODEL

# Create your views here.
def register_views(request):

    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        print("User registred successfully")
        if form.is_valid() :
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, Your account was created successfully.")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1']
            )
            login(request, new_user)
            return redirect("store:index")
    else:
        form = UserRegisterForm()
    
    context = {
        'form' : form
    }
    
    return render(request,"userauths/sign-up.html", context)


def login_views(request):
    if request.user.is_authenticated:
        messages.warning(request, "Hey you are already Logged In.")
        return redirect("store:index")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        try:
            user = User.objects.get(email=email)
        except :
            messages.warning(request, f"User with email {email} doesn't exist")

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, "You are logged in.")
            return redirect("store:index")
        else:
            messages.warning(request, "Invalid credentials. Please try again.")
            
    context = {
       
    }       
    return render(request,"userauths/sign-in.html", context)

def logout_views(request):
    logout(request)
    messages.success(request, "You logged out.")
    return redirect("userauths:sign-in")

templates/userauths/sign-in.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<div class="hero">
    <div class="container">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-13 col-sm-11 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
          <div class="card border border-light-subtle rounded-3 shadow-sm">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="text-center mb-3">
                <h2 class="h4 text-center">Login</h2>
              </div>
              <h2 class="fs-6 fw-normal text-center text-secondary mb-4">Sign in to your account</h2>
              <form action="" method="POST">
                <div class="row gy-2 overflow-hidden">
                    {% csrf_token %}
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      <input type="email" class="form-control" name="email" id="email" placeholder="name@example.com" required>
                      <label for="email" class="form-label">Email</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      <input type="password" class="form-control" name="password" id="password" value="" placeholder="Password" required>
                      <label for="password" class="form-label">Password</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-flex gap-2 justify-content-between">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" name="rememberMe" id="rememberMe">
                        <label class="form-check-label text-secondary" for="rememberMe">
                          Keep me logged in
                        </label>
                      </div>
                      <a href="#!" class="link-primary text-decoration-none">Forgot password?</a>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-grid my-3">
                      <button class="btn btn-primary btn-lg" type="submit">Log in</button>
                    </div>
                  </div>
                  <div class="col-12">
                    <p class="m-0 text-secondary text-center">Don't have an account? <a href="{% url 'userauths:sign-up' %}" class="link-primary text-decoration-none">Sign up</a></p>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
</div>	
{% endblock content %}

templates/userauths/sign-up.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

<div class="hero">
    <div class="container">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-13 col-sm-11 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
          <div class="card border border-light-subtle rounded-3 shadow-sm">
            <div class="card-body p-3 p-md-4 p-xl-5">
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <strong>{{form.errors}}</strong>
                    </div>
                {% endif %}
                <div class="row">
                <div class="col-12">
                    <div class="mb-5">
                    <h2 class="h4 text-center">Registration</h2>
                    <h3 class="fs-6 fw-normal text-secondary text-center m-0">Enter your details to register</h3>
                    </div>
                </div>
                </div>
                <form action="" method="POST">
                    <div class="row gy-3 overflow-hidden">
                        {% csrf_token %}
                        <div class="col-12">
                        <div class="form-floating mb-3">
                            {{form.username}}
                            <label for="firstName" class="form-label">Username</label>
                        </div>
                        </div>
                        <div class="col-12">
                        <div class="form-floating mb-3">
                            {{form.email}}
                            <label for="firstName" class="form-label">Email</label>
                        </div>
                        </div>
                        <div class="col-12">
                        <div class="form-floating mb-3">
                            {{form.password1}}
                            <label for="firstName" class="form-label">Password</label>
                        </div>
                        </div>
                        <div class="col-12">
                        <div class="form-floating mb-3">
                            {{form.password2}}
                            <label for="firstName" class="form-label">Confirm Password</label>
                        </div>
                        </div>
                        <div class="col-12">
                            <div class="d-grid">
                                <button class="btn bsb-btn-xl btn-primary" type="submit">Sign up</button>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="row">
                <div class="col-12">
                    <hr class="mt-5 mb-4 border-secondary-subtle">
                    <p class="m-0 text-secondary text-center">Already have an account? <a href="{% url 'userauths:sign-in' %}" class="link-primary text-decoration-none">Sign in</a></p>
                </div>
                </div>
                <div class="row">
                <div class="col-12">
                    <h6 class="mt-4 mb-3" style="font-weight: 1;">Or continue with</h6>
                    <div class="d-flex gap-2 gap-sm-3 justify-content-center">
                    <a href="#!" class="btn btn-lg btn-outline-danger p-3 lh-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
                        <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z" />
                        </svg>
                    </a>
                    <a href="#!" class="btn btn-lg btn-outline-primary p-3 lh-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                        </svg>
                    </a>
                    <a href="#!" class="btn btn-lg btn-outline-info p-3 lh-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
                        </svg>
                    </a>
                    <a href="#!" class="btn btn-lg btn-outline-dark p-3 lh-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-apple" viewBox="0 0 16 16">
                        <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z" />
                        <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z" />
                        </svg>
                    </a>
                    </div>
                </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</div>
</div>	
{% endblock content %}