ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),   
    path("", include("store.urls")),
    path("user/", include("userauths.urls")),
]

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from store.views import index
from .views import shop_view, about_view, contact_view, blog_view, services_view , cart_view,checkout_view, search_view, details_view,cart_vieww, payment_completed_view, chambre_view, cuisine_view, salon_view
app_name = "store"

urlpatterns = [
    path("", index, name="index"),
    path("shop/", shop_view, name="shop_view"),
    path("about/", about_view, name="about_view"),
    path("contact/", contact_view, name="contact_view"),
    path("blog/", blog_view, name="blog_view"),
    path("services/", services_view, name="services_view"),
    path("cart/<pid>", cart_view, name="cart_view"),
    path("cart/", cart_vieww, name="cart_vieww"),
    path("cart-v/", cart_vieww, name="cart_v"),

    path("checkout/", checkout_view, name="checkout_view"),
    path("search/", search_view, name="search_view"),
    path("details/<pid>",details_view ,name="details_view"),
    path('paypal/', include('paypal.standard.ipn.urls')),

    path("paiement_completed/",payment_completed_view ,name="payment_completed"),
    path("chambre/",chambre_view ,name="chambre_view"),
    path("cuisine/",cuisine_view ,name="cuisine_view"),
    path("salon/",salon_view ,name="salon_view"),
]

store/models.py
from pyexpat import model
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import User


STATUS_CHOICE = (
    ("process", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
)

STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
)

RATING = (
    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★"),
)

def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

# Create your models here.
class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=20, prefix="cat", alphabet="abcdefgh12345")
    title = models.CharField(max_length=100, default="Meuble")
    image = models.ImageField(upload_to="category", default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return('<img src="%s" width="50" height="50" />' %(self.image.url))
    
    def __str__(self):
        return self.title
    
class Tags(models.Model):
    pass

class Vendor(models.Model): 
    vid = ShortUUIDField(unique=True, length=10, max_length=20, prefix="cat", alphabet="abcdefgh12345")
    
    title = models.CharField(max_length=100, default="Dikea")
    image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    descreption = models.TextField(null=True, blank=True, default="I am Amazing vendor")

    adress = models.CharField(max_length=100, default="123 Main Street.")
    contact = models.CharField(max_length=100, default="+123 (456) 789")
    chat_resp_time = models.CharField(max_length=100, default="1")
    shipping_on_time = models.CharField(max_length=100, default="100")
    authentic_rating = models.CharField(max_length=100, default="100")
    days_return = models.CharField(max_length=100, default="100")
    warranty_period = models.CharField(max_length=100, default="100")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
   
    class Meta:
        verbose_name_plural = "Vendors"

    def vendor_image(self):
        return('<img src="%s" width="50" height="50" />' %(self.image.url))
    
    def __str__(self):
        return self.title

class Product(models.Model): 
    pid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefgh12345")
    
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    title = models.CharField(max_length=100, default="Good Quality")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    descreption = models.TextField(null=True, blank=True, default="This is the product")
    
    price = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="1.99")
    old_price = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="2.99")
    
    specifications = models.TextField(null=True, blank=True)
    #tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True)

    product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=False)

    sku = ShortUUIDField(unique=True, length=4, max_length=10, prefix="sku", alphabet="1234567890")
    date = models.DateTimeField(auto_now_add=True)
   # updated = models.DateTimeField(null=False, blank=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Products"

    def product_image(self):
        return('<img src="%s" width="50" height="50" />' %(self.image.url))
    
    def __str__(self):
        return self.title
    
    def get_percentage(self):
        new_price = (self.price / self.old_price) * 100
        return new_price
    
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images", default="product.jpg")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Images"



####################################### Cart, Order, OrderItems and Address ######################################
####################################### Cart, Order, OrderItems and Address ######################################
####################################### Cart, Order, OrderItems and Address ######################################
####################################### Cart, Order, OrderItems and Address ######################################

class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="1.99")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=30, default="processing")

    class Meta:
        verbose_name_plural = "Cart Order"

class CartOrderItems(models.Model):
    order = models.ForeignKey(User, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=200)
    product_status = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.IntegerField(default=0)
    qty = models.CharField(max_length=200, default="1")
    price = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="1.99")
    total = models.DecimalField(max_digits=99999999999999, decimal_places=2, default="1.99")

    class Meta:
        verbose_name_plural = "Cart Order_Items"
    
    def order_img(self):
        return('<img src="/media/%s" width="50" height="50" />' %(self.image))
    

####################################### Product Review, wishlists, Adress ######################################
####################################### Product Review, wishlists, Adress ######################################
####################################### Product Review, wishlists, Adress ######################################
####################################### Product Review, wishlists, Adress ######################################

class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)    

    class Meta:
        verbose_name_plural = "Product Reviews"

    def __str__(self):
        return self.product.title
    
    def get_rating(self):
        return self.rating

class wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)    

    class Meta:
        verbose_name_plural = "wishlists"

    def __str__(self):
        return self.product.title
    
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address"

store/views.py
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponse
from store.models import Product, Vendor, Category, CartOrder, CartOrderItems, ProductImages, ProductReview, wishlist, Address
#from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
# Create your views here.
#@login_required
def index(request):
   if request.user.is_authenticated:
      categories=Category.objects.all()
      context = {
         'categories':categories
      }
      return render(request, 'store/index.html',context)
   else:
      return render(request,"userauths/sign-in.html")


def shop_view(request):
   if request.user.is_authenticated:
      products = Product.objects.all()
      context = {
      'products': products
      }
      return render(request,'store/shop.html',context)
   else:
      return render(request,"userauths/sign-in.html")

def about_view(request):
   
   return render(request,'store/about.html')

def contact_view(request):
   return render(request,'store/contact.html')

def blog_view(request):
   return render(request, 'store/blog.html')

def services_view(request):
   return render(request, 'store/services.html')

def cart_vieww(request):
   if request.user.is_authenticated:
      return render(request,'store/cart.html')
   else:
      return render(request,"userauths/sign-in.html")

def cart_view(request,pid):
   product=Product.objects.get(pid=pid)
   context = {
        'p': product
    }
   return render(request, 'store/cart.html',context)

def checkout_view(request):
   if request.user.is_authenticated:
      return render(request, 'store/checkout.html')
   else:
      return render(request,"userauths/sign-in.html")

def search_view(request):
   products = Product.objects.all()
   query1 = request.GET.get("q")
   query2 = request.GET.get("choices-single-defaul")
   min_price = request.GET.get("min")
   max_price = request.GET.get("max")
   print(min_price)
   print(max_price)
   print(query1)
   
   

   if query1 !='' and query1 is not None:
      products = products.filter(title__icontains=query1, descreption__icontains=query1)

   if (query2=='Salon'):
      category = Category.objects.get(title='Salon')
      cid = category.cid
      cat = Category.objects.get(cid=cid)
      products = products.filter(category=cat)

   if (query2=='Cuisine'):
      category = Category.objects.get(title='Cuisine')
      cid = category.cid
      cat = Category.objects.get(cid=cid)
      products = products.filter(category=cat)

   if (query2=='Chambre'):
      category = Category.objects.get(title='Chambre')
      cid = category.cid
      cat = Category.objects.get(cid=cid)
      products = products.filter(category=cat)

   if min_price is not None:
        products = products.filter(price__gte=min_price)

   if max_price is not None:
      products = products.filter(price__lte=max_price)

   context ={
      'products': products,
   }
   return render(request,'store/search.html', context)

   
def details_view(request,pid):
   product=Product.objects.get(pid=pid)
   # product= get_object_or_404(Product,pid=pid)
   context = {
        'p': product
    }
   return render(request, 'store/details.html',context)

def add_to_cart(request):
   cart_product={}
   cart_product[str(request.GET[{"id"}])]={
      'title':request.GET[{"title"}],
      'price':request.GET[{"price"}],
   }
   if 'cart_data_obj' in request.session:
      if str(request.GET[{"id"}]) in request.session['cart_data_obj']: 
         cart_data=request.session['cart_data_obj']
         cart_data[str(request.GET[{"id"}])] 
      

from django.urls import reverse
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm

def checkout_view(request):   
   return render(request,'store/checkout.html')  
   # host = request.get_host()
   # paypal_dict = {
   #    'business' : settings.PAYPAL_RECEIVER_EMAIL,
   #    'amount':'200',
   #    'item_name':"Order-Itrm-No-3",
   #    'invoice':'INVOICE_NO_3',
   #    'currency_code':"USD",
   #    'notify_url':'http://{}{}'.format(host, reverse("store:paypal-ipn")),
   #    'return-url': 'http://{}{}'.format(host, reverse("store:payment_completed")),
   # }

   # paypal_payment_button = PayPalPaymentsForm(initial=paypal_dict)

   # cart_total_amount = 319.00
   # if 'cart_data_obj' in request.session:
   #    return render(request, "store/checkout.html", {"cart_data":request.session['cart_data_obj'], 'cart_total_amount':cart_total_amount, 'paypal_payment_button':paypal_payment_button})

      #  if request.method == 'POST':
      #   # Récupérer les données du produit à partir de la requête POST
      #   product_id = request.POST.get('product_id')
      #   product_price = request.POST.get('product_price')
      #   product_image = request.POST.get('product_image')
      #   # Ajoutez d'autres champs requis
        
      #   # Vous pouvez également vérifier si l'utilisateur est connecté ou si le produit existe, etc.
        
      #   # Créer une instance de CartOrderItems pour représenter le produit dans le panier
      #   cart_item = CartOrderItems.objects.create(
      #       order=request.user,  # Ou toute autre méthode que vous utilisez pour récupérer l'utilisateur connecté
      #       item=product_id,  # Utilisez l'ID du produit comme référence
      #       price=product_price,
      #       image=product_image,
      #       # Ajoutez d'autres champs requis comme la quantité, le numéro de facture, etc.
      #   )
        
      #   # Vous pouvez également renvoyer une réponse JSON pour indiquer le succès de l'ajout au panier
      #   return JsonResponse({'success': True})

def payment_completed_view(request):
   return render(request, 'store/thankyou.html')

def chambre_view(request):
   products = Product.objects.all()
   
   category = Category.objects.get(title='Chambre')
   cid = category.cid
   cat = Category.objects.get(cid=cid)
   products = products.filter(category=cat)

   context ={
      'products': products,
   }
   return render(request,'store/chambre.html', context)

def salon_view(request):
   products = Product.objects.all()
   
   category = Category.objects.get(title='Salon')
   cid = category.cid
   cat = Category.objects.get(cid=cid)
   products = products.filter(category=cat)

   context ={
      'products': products,
   }
   return render(request,'store/salon.html', context)

def cuisine_view(request):
   products = Product.objects.all()
   
   category = Category.objects.get(title='Cuisine')
   cid = category.cid
   cat = Category.objects.get(cid=cid)
   products = products.filter(category=cat)

   context ={
      'products': products,
   }
   return render(request,'store/cuisine.html', context)

templates/store/cart-v.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>Cart</h1>
							</div>
						</div>
						<div class="col-lg-7">
							
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->

		

		<div class="untree_co-section before-footer-section">
            <div class="container">
              <div class="row mb-5">
                <form class="col-md-12" method="post">
                 
                </form>
              </div>
        
              <div class="row">
                <div class="col-md-6">
                  <div class="row mb-5">
                    <div class="col-md-6">
                      <button class="btn btn-outline-black btn-sm btn-block">Continue Shopping</button>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 pl-5">
                  <div class="row justify-content-end">
                    <div class="col-md-7">
                      <div class="row">
                        <div class="col-md-12 text-right border-bottom mb-5">
                          <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
		

		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/tiny-slider.js' %}"></script>
		<script src="{% static 'js/custom.js' %}"></script>
	</body>

</html>
{% endblock content %}

templates/store/cart.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}

		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>Cart</h1>
							</div>
						</div>
						<div class="col-lg-7">
							
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->

		<div class="untree_co-section before-footer-section">
            <div class="container">
              <div class="row mb-5">
                <form class="col-md-12" method="post">
                  <div class="site-blocks-table">
                    <table class="table">
                      <thead>
                        <tr>
                          <th class="product-thumbnail">Image</th>
                          <th class="product-name">Product</th>
                          <th class="product-price">Price</th>
                          <th class="product-total">Total</th>
                          <th class="product-remove">Remove</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          {% if p is not None %}
                          <td class="product-thumbnail">
                            <img src="{{p.image.url}}" alt="Image" class="img-fluid">
                          </td>
                          <td class="product-name">
                            <h2 class="h5 text-black">{{p.title}}</h2>
                          </td>
                          <td>{{p.price}}</td>
                          <h2 class="h5 text-black">{{p.title}}</h2>

                          <td>{{p.price}}</td>
                          <td><a href="{% url 'store:cart_v' %}" class="btn btn-black btn-sm">X</a></td>
                        </tr>
                        {% endif %}
                      </tbody>
                    </table>
                  </div>
                </form>
              </div>
        
              <div class="row">
                <div class="col-md-6">
                  <div class="row mb-5">
                    <div class="col-md-6 mb-3 mb-md-0">
                      <a class="btn btn-outline-black btn-sm btn-block" href="{% url 'store:shop_view' %}">Continue Shopping</a>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 pl-5">
                  <div class="row justify-content-end">
                    <div class="col-md-7">
                      <div class="row">
                        <div class="col-md-12 text-right border-bottom mb-5">
                          <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                        </div>
                      </div>
                      <div class="row mb-5">
                        <div class="col-md-6">
                          <span class="text-black">Total</span>
                        </div>
                        <div class="col-md-6 text-right">
                          <strong class="text-black">{{p.price}}</strong>
                        </div>
                      </div>
        
                      <div class="row">
                        <div class="col-md-12">
							            <button class="btn btn-black btn-lg py-3 btn-block" onclick="window.location='{% url 'store:checkout_view' %}'" id="checkout-button" data-product-id="{{ product_id }}">Proceed To Checkout</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
{% endblock content %}

templates/store/details.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}
  

  <div class="untree_co-section product-section before-footer-section">
    <div class="container">
      <div class="row">
        <!-- Start Column 1 -->
        <div class="we-help-section">
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-lg-7 mb-5 mb-lg-0">
						<div class="imgs-grid">
							<div class="grid grid-1"><img src="{{p.image.url}}" ></div>
							
						
						</div>
					</div>
					<div class="col-lg-5 ps-lg-5">
            <h2 class="section-title mb-4" style="color: black;font-size: 25px; " >{{p.category.title}}</h2>
						<h2 class="section-title mb-4" style="color: black; font-weight: bold;" >{{p.title}}</h2>
						

						<ul class="list-unstyled custom-list my-4">
							{% if p.old_price != p.price %}
                <h1 style="color: gray; font-size: 20px; font-weight: bold;text-decoration: line-through;">${{ p.old_price }}</h1>
              {% endif %}
							<h1 style="color: black; font-size: 25px;font-weight: bold;">${{p.price}}</h1>
              <p style="color: black;">{{p.descreption}}</p>
              <span style="color: black;">We offer a wide range of styles and colors to choose from, so you can find the perfect fit</span>
						</ul>
             <!-- <button type="submit" class="btn btn-primary" id="add-to-cart" onclick="cart" >Add to Cart</button>
				<script>
          function cart() {
            window.location.href = "{% url 'store:cart_view' p.pid %}";
  }                    
        </script> -->
        <a href="{% url 'store:cart_view' p.pid %}" class="btn btn-primary">ADD </a>
            </div>
				</div>
			</div>
		</div>
        <!-- End Column 1 -->
      </div>
    </div>
  </div>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/tiny-slider.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  
</body>
</html>
{% endblock content %}

templates/store/index.html
{% extends 'partial/base.html' %}
{% load static %}
{% block content %}
		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>Welcome to<span clsas="d-block"> Univers du Meuble</span></h1>
								<p class="mb-4">Discover a curated selection of stylish furniture to elevate your interior with both style and comfort on l'Univers du Meuble. From luxurious sofas to modern tables, each piece is carefully chosen to offer quality and elegance. Transform your home into a functional living space today.</p>
								<p><a href="{% url 'store:shop_view' %}" class="btn btn-secondary me-2">Shop Now</a><a href="#" class="btn btn-white-outline">Explore</a></p>
							</div>
						</div>
						<div class="col-lg-7">
							<div class="hero-img-wrap">
								<img src="{% static 'assets/images/couch23.png' %}" class="img-fluid">
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->

		<!-- Start Product Section -->
		<div class="product-section">
			<div class="container">
				<div class="row">

					<!-- Start Column 1 -->
					<div class="col-md-12 col-lg-3 mb-5 mb-lg-0">
						<h2 class="mb-4 section-title">Our categories </h2>
						<p class="mb-4">Explore our wide range of furniture categories including living room, kitchen, and bedroom essentials, each tailored to meet your specific needs. </p>
						<p><a href="shop.html" class="btn">Explore</a></p>
					</div> 
					<!-- End Column 1 -->

					<!-- Start Column 2 -->
					<div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
						<a class="product-item" href="{% url 'store:chambre_view' %}">	
							<img src="{% static 'assets/images/Chambre.jpeg' %}" class="img-fluid product-thumbnail">
							<h3 class="product-title">Chambre</h3>
						</a>
					</div> 
					<div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
						<a class="product-item" href="{% url 'store:cuisine_view' %}">	
							<img src="{% static 'assets/images/Cuisine.jpeg' %}" class="img-fluid product-thumbnail">
							<h3 class="product-title">Cuisine</h3>
						</a>
					</div> 
					<div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
						<a class="product-item" href="{% url 'store:salon_view' %}">	
							<img src="{% static 'assets/images/Salon.jpeg' %}" class="img-fluid product-thumbnail">
							<h3 class="product-title">Salon</h3>
						</a>
					</div> 
					<!-- End Column 2 -->
				</div>
			</div>
		</div>
		<!-- End Product Section -->

		<!-- Start Why Choose Us Section -->
		<div class="why-choose-section">
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-lg-6">
						<h2 class="section-title">Why Choose Us</h2>
						<p>Choose us for your furniture needs because we prioritize quality, craftsmanship, and customer satisfaction above all else.</p>

						<div class="row my-5">
							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static 'assets/images/truck.svg' %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Fast &amp; Free Shipping</h3>
									<p>Enjoy our lightning-fast and complimentary shipping services!.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static 'assets/images/bag.svg' %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Easy to Shop</h3>
									<p>Browse effortlessly through our user-friendly interface!.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static 'assets/images/support.svg' %}" alt="Image" class="imf-fluid">
									</div>
									<h3>24/7 Support</h3>
									<p>Access our round-the-clock customer support for any queries or concerns!.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static 'assets/images/return.svg' %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Hassle Free Returns</h3>
									<p>Experience hassle-free returns with our simple and efficient process!.</p>
								</div>
							</div>

						</div>
					</div>

					<div class="col-lg-5">
						<div class="img-wrap">
							<img src="{% static 'assets/images/why-choose-us-img.jpg' %}" alt="Image" class="img-fluid">
						</div>
					</div>

				</div>
			</div>
		</div>
		<!-- End Why Choose Us Section -->

		<!-- Start We Help Section -->
		<div class="we-help-section">
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-lg-7 mb-5 mb-lg-0">
						<div class="imgs-grid">
							<div class="grid grid-1"><img src="{% static 'assets/images/img-grid-1.jpg' %}" alt="Untree.co"></div>
							<div class="grid grid-2"><img src="{% static 'assets/images/image2.jpg' %}" alt="Untree.co"></div>
							<div class="grid grid-3"><img src="{% static 'assets/images/image3.jpg' %}" alt="Untree.co"></div>
						</div>
					</div>
					<div class="col-lg-5 ps-lg-5">
						<h2 class="section-title mb-4">We Help You Make Modern Interior Design</h2>
						<p>Let us assist you in creating a modern interior design that reflects your style and personality. With our expertise and guidance, your space will transform into a contemporary oasis that you'll love coming home to. Whether you're looking for sleek minimalism or bold statement pieces, we've got you covered.</p>

						<ul class="list-unstyled custom-list my-4">
							<li>Our curated collection of furniture and decor items is designed to cater to modern tastes</li>
							<li>We offer a wide range of styles and colors to choose from, so you can find the perfect fit</li>
						</ul>
						
					</div>
				</div>
			</div>
		</div>
		<!-- End We Help Section -->

			
{% endblock content %}